### PR TITLE
Initial fallback implementation

### PR DESCRIPTION
**Pull request by AlexanderKalistratov**

### CODE REVIEW

**Review by DrTodd13 — COMMENTED** [review]
@AlexanderKalistratov One general thing I'm curious about.  Is it the case that nothing gets added to the builder for the parent function before the lowering of the outlined parfor body that may fail?  If anything gets added at all then it may be a problem if you reset things and go through another path that maybe starts to add similar code for the CPU fallback.  Maybe such code isn't an issue if it isn't used and is therefore eliminated but I'm curious about what you think about this issue.

**Comment by AlexanderKalistratov** [comment]
@DrTodd13 At the moment parent function doesn't add any device specific instructions, so there is no such issue right now. In case it would add device specific instructions though it would become a problem and different solution would be required.

**Comment by AlexanderKalistratov** [comment]
Current solution doesn't support case when parent function insert any device specific instructions/do device specific optimization.
To address such case different approach should be implemented.

**Comment by AlexanderKalistratov** [comment]
@diptorupd I've added comment about how lowering happens and limitation of such approach.

https://github.com/IntelPython/numba/pull/8/files#diff-d8989c7f1e14dfa24fbb582a225d6442R973

**Comment by diptorupd** [comment]
Looks good. Thanks @AlexanderKalistratov.

**Pull request merged**
