### PR TITLE
Refactoring ParforDiagnostics

### PR DESCRIPTION
**Pull request by 1e-to**
We need to be able to get "all_lines" to reuse it in our ExtendedParforDiagnostics to avoid code duplication.
Also now "dump" function is too complicated so this refactoring was made.

### CODE REVIEW

**Comment by reazulhoque** [comment]
We need to make sure this PR is against the correct branch before we start merging it. I will test it once we know this issue is fixed.

**Comment by reazulhoque** [comment]
Too many changes got introduced as part of the porting process from pydppl to patched. We need to clean it up to see the actual changes @1e-to.

**Review by PokhodenkoSA — APPROVED** [review]
LGTM.

**Review by PokhodenkoSA — CHANGES_REQUESTED** [review]
Please, reset to branch `patched` and cherry-pick your commit. Then target the PR to `patched`.

**Comment by 1e-to** [comment]
Reopen in https://github.com/IntelPython/numba/pull/135

**Pull request closed without merging**
