### PR TITLE
Patch for disable emit_environment_object() for dppl context

### PR DESCRIPTION
**Pull request by PokhodenkoSA**
Change introduced in 947b407 by @reazulhoque.

### CODE REVIEW

**Comment by PokhodenkoSA** [comment]
Try to remove and run checks. @diptorupd faced segfaults some time ago without this modifications.
If tests will pass then it could be removed.

**Comment by diptorupd** [comment]
Previously, we were running `spirv-val` on the SPIR-V binary we generated from Numba. The change was added by me to avoid a `spirv-val` error that is caused because by default Numba passes a global pointer as an argument to the generated function. The reasoning most likely is that a device function cannot access a global pointer in the host address space and thus it should be disallowed.

However, we never pass anything using the global pointer and it is never accessed, so it might be fine just reverting the change. We have turned off `spirv-val` a while back to get around other issues that are benign but flagged by `spirv-val`, so reverting the change should not cause a `spirv-val` error. 

If after reverting the change, the tests pass then we should merge.

@PokhodenkoSA If we remove the code in `lowering.py` please also remove this line in our `target.py` 
https://github.com/IntelPython/numba/blob/de35af55d295f1677cca76646691d8c51c79d3cf/numba/dppl/target.py#L97

**Comment by PokhodenkoSA** [comment]
> @PokhodenkoSA If we remove the code in `lowering.py` please also remove this line in our `target.py`
> https://github.com/IntelPython/numba/blob/de35af55d295f1677cca76646691d8c51c79d3cf/numba/dppl/target.py#L97

Created for it - https://github.com/IntelPython/numba-dppy/pull/6

**Comment by PokhodenkoSA** [comment]
Tested locally - no new failed tests. Will merge it.

**Pull request merged**
