### PR TITLE
Fix ParforDiagnostic errors

### PR DESCRIPTION
**Pull request by 1e-to**
Fix errors in numba.tests which was appear by https://github.com/IntelPython/numba/pull/135

### CODE REVIEW

**Comment by PokhodenkoSA** [comment]
@1e-to did you update upstream PR too?

**Comment by 1e-to** [comment]
> did you update upstream PR too?

Yes

**Comment by PokhodenkoSA** [comment]
What tests failed?

**Comment by 1e-to** [comment]
> What tests failed?

No, everything is okay
https://github.com/numba/numba/pull/6545

**Comment by PokhodenkoSA** [comment]
What tests failed before this PR?

**Comment by 1e-to** [comment]
> What tests failed before this PR?

ERROR: test_allocation_hoisting (numba.tests.test_parfors.TestParforsDiagnostics)
ERROR: test_function_replacement (numba.tests.test_parfors.TestParforsDiagnostics)
ERROR: test_nested_prange (numba.tests.test_parfors.TestParforsDiagnostics)

**Comment by PokhodenkoSA** [comment]
Tested locally - tests passed.

**Pull request merged**
