### PR TITLE
Remove _remove_unneeded_phis()

### LINKED ISSUE #51: Clean differences with Numba 0.51.2 we did not do
During merge with Numba 0.51.2 like #50 there could be changes that are not in upstream Numba and was not added by us.

This code could be searched by showing all diffs and see who are author of the code. If author is not from IntelPython then code should be reverted to upstream Numba code.

### PR DESCRIPTION
**Pull request by PokhodenkoSA**
This function was removed for release0.50 in commit e56675546.
Due to some merging error this commit was not applied to our
main branch.

@reazulhoque if you have some info about this function and why it was no deleted, please, inform me.

@Hardcode84 this function could influence on some issues we could have from Numba 0.50. This function was removed in official Numba 0.50 but was in our code and was in our package. Possibly, you have faced some problems related to this. Please, inform me.

Closes #51.

### CODE REVIEW

**Comment by reazulhoque** [comment]
@PokhodenkoSA : I have no idea why this was not deleted from 50.0 to 51. I can not think of any reason.

**Comment by PokhodenkoSA** [comment]
> @PokhodenkoSA : I have no idea why this was not deleted from 50.0 to 51. I can not think of any reason.

Thank you @reazulhoque. I think we do not need this code.

**Comment by PokhodenkoSA** [comment]
@reazulhoque If you do not know then we do not need this code.

**Comment by reazulhoque** [comment]
I think so.

**Comment by PokhodenkoSA** [comment]
As we discussed with @Hardcode84 there is no info about this function impact.

**Pull request merged**
