### PR TITLE
Extension point: numba config options

### PR DESCRIPTION
**Pull request by PokhodenkoSA**
This config options could be moved to extension. But if we want to
access some config options via numba.config then Numba should provide
extension point for this.

### CODE REVIEW

**Comment by PokhodenkoSA** [comment]
From @diptorupd: consider the same from CUDA.

**Comment by reazulhoque** [comment]
We can move this to the extension, should this PR be merged after we have made the addition in the extension first?

**Comment by PokhodenkoSA** [comment]
> should this PR be merged after we have made the addition in the extension first?

I have created this PR not for removing code but for starting discussion about it.

**Comment by PokhodenkoSA** [comment]
Should be moved to `numba-dppy`.

**Comment by PokhodenkoSA** [comment]
Related to https://github.com/IntelPython/numba-dppy/pull/15

**Pull request merged**
