### PR TITLE
Remove unary_sqrt_extern() used for sqrt_impl

### PR DESCRIPTION
**Pull request by PokhodenkoSA**
This possibly could be a function required to move to upstream but also
it could be a not intended function.

This function was created in b4a325d59 by @DrTodd13.
Then there was a long branch dedicated to PVC and in 947b40788 it was merged with master of Numba by @reazulhoque.
It was released first time in `0.49.1+dppy0.4.0`.

@DrTodd13 if this function is not important for the current state of Numba DPPY the I would like to revert it to release0.51 branch of Numba.

### CODE REVIEW

**Review by reazulhoque — COMMENTED** [review]
I spoke with Todd about this a while back when we first started this effort. I tried commenting the change and ran math.sqrt test (I wrote it), I did not find any problem. May be you want to replicate what I did before we decide to remove this piece of code.

**Comment by PokhodenkoSA** [comment]
> I tried commenting the change and ran math.sqrt test (I wrote it), I did not find any problem.

Do you have some code for it? Did you write a new test for `math.sqrt`? Could you please provide a link to it?

> May be you want to replicate what I did before we decide to remove this piece of code.

Do you mean remove this code and run tests? Or you have made some work about it and I should take it into consideration too? Could you please provide a link to it or describe it in more details?

**Comment by reazulhoque** [comment]
Hi @PokhodenkoSA I wrote a simple test calling `math.sqrt`, I do not have it currently.

I meant to write similar test calling `math.sqrt` and make sure removing this code does not have any affect.

**Comment by PokhodenkoSA** [comment]
After several discussions with @DrTodd13 and @reazulhoque: this code was introduced not for dppy functionality and could be removed if it will not break tests.

**Pull request merged**
