### PR TITLE
Patch for change numpy functions mapping

### PR DESCRIPTION
**Pull request by PokhodenkoSA**
Changed in 8ccfd36 and a77eab6 by @reazulhoque.
Possibly this 2 changes are not related to each other.

### CODE REVIEW

**Comment by PokhodenkoSA** [comment]
There are 2 unrelated changes.

1. Need to redesign Numba and proposed to Anaconda:
- `ufunc_db` should be context dependent. It should not be a global variable. Default values could be global, but access to it should be via context.

2. Need to redesign Numba and proposed to Anaconda:
- Access to `replace_functions_map` should be via PreParforPass instance. It should not be a global variable.

**Comment by PokhodenkoSA** [comment]
Moved to upstream for starting discussion:
- numba#6467
- numba#6468

**Comment by PokhodenkoSA** [comment]
@reazulhoque 
As numba#6467 and numba#6468 are merged I think we can close this ticket.

**Comment by reazulhoque** [comment]
I agree. Let us close it.

**Pull request closed without merging**
